### ISSUE TITLE
LLaVA：image loading and processing code

### ISSUE THREAD

**Issue by zhouhao028** [mapluisch/LLaVA-CLI-with-multiple-images#1]
Thank you for your work, Could you please provide existing image loading and processing code? It means a lot to me!

**Comment by mapluisch** [comment]
Hey, no problem!

In my script, there's already code for loading and concatenating the images:

```
def load_image(image_file):
    if image_file.startswith('http://') or image_file.startswith('https://'):
        response = requests.get(image_file)
        image = Image.open(BytesIO(response.content)).convert('RGB')
    else:
        image = Image.open(image_file).convert('RGB')
    return image

def concatenate_images(images):
    width = max(img.width for img in images)
    total_height = sum(img.height for img in images) + 20 * (len(images) - 1)

    new_img = Image.new('RGB', (width, total_height), (0, 0, 0))

    current_height = 0
    for img in images:
        new_img.paste(img, (0, current_height))
        current_height += img.height + 20  # adding a 20px black bar

    return new_img
```

Or is there a specific img loading / processing that you have in mind that I haven't implemented?
As long as you return the PIL image in `load_image` and do the same for the concatenated processed image in `concatenate_images`, you can just replace my code and add your own, if you want to.

**Comment by zhouhao028** [comment]
Thank you for your help. I have another question. Can the input photo be two consecutive photos? Thank you again for your help.

**Comment by mapluisch** [comment]
> Thank you for your help. I have another question. Can the input photo be two consecutive photos? Thank you again for your help.

You're very welcome. Just to better understand your question - do you mean consecutive, as in consecutive frames of e.g. a video, or consecutive as in placed next to each other for inference? Either way, the answer would be yes.

If it's the second option, you can adjust my function `concatenate_images` from above to simply increase the width instead of the height and paste the image to x = img1's width (instead of 0).

Hope that helps, and if not, feel free to ask :)

**Comment by zhouhao028** [comment]
Thank you for your help, sorry for not specifying it. My question is whether it is possible to input two different photos at the same time, such as photo 1 and photo 2, and whether it is to modify the height in concatenate_images, which is very helpful to me. Thank you very much for your help!

**Comment by mapluisch** [comment]
Ah, I see. Yep, the function I've provided is specifically for multiple images - you can specify two or more images. The `concatenate_images` function that's currently included in the source code (which is the one I've posted above) simply merges two or more images into a single image by pasting them above one another. For that, it basically creates a fresh image with the width of the widest image and the combined height of all images (plus some added padding). This merged image is then used for inference 😄

**Comment by zhouhao028** [comment]
Thank you for your help. It was very useful to me. Thank you again

**Comment by mapluisch** [comment]
Sure, you're welcome! Feel free to reach out if you need further help - I will close this issue for now.
