### ISSUE TITLE
ModuleNotFoundError: No module named 'llava'

### ISSUE THREAD

**Issue by ilileun** [mapluisch/LLaVA-CLI-with-multiple-images#2]
Let's take a look at how to get started with the code. I would appreciate it if you could send it to me.

**Comment by mapluisch** [comment]
Hey ilileun,

sorry for the late response. My script is based on LLaVA's CLI script ([LLaVA GitHub repo](https://github.com/haotian-liu/LLaVA).
Please follow the install tutorial of LLaVA until you can run and use the included Gradio app and potentially launch a model worker (you do not need to setup SGLang):

1. Clone this repository and navigate to LLaVA folder
```bash
git clone https://github.com/haotian-liu/LLaVA.git
cd LLaVA
```

2. Install Package
```Shell
conda create -n llava python=3.10 -y
conda activate llava
pip install --upgrade pip  # enable PEP 660 support
pip install -e .
```

3. Install additional packages for training cases
```
pip install -e ".[train]"
pip install flash-attn --no-build-isolation
```

At that point, you will have a conda environment for LLaVA. Then, simply put my script into your LLaVA directory and launch it while in the conda environment. The script will take care of loading the checkpoint shards etc. Just make sure to use the correct model, in case you'd prefer the 7B version 🙂 

Hope that helps!
